spring.application.name=uco-parking
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ucoparking;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.webflux.base-path=/uco-parking
logging.level.reactor=INFO
logging.level.co.edu.uco=DEBUG
